DEFAULT_UNIVERSE = [
    "1000BONKUSDT",
    "1000FLOKIUSDT",
    "1000PEPEUSDT",
    "AAVEUSDT",
    "ADAUSDT",
    "APTUSDT",
    "ARBUSDT",
    "ARKMUSDT",
    "ATOMUSDT",
    "AVAXUSDT",
    "AXSUSDT",
    "BCHUSDT",
    "DOGEUSDT",
    "DOTUSDT",
    "ENAUSDT",
    "ENSUSDT",
    "ETCUSDT",
    "FILUSDT",
    "GALAUSDT",
    "HBARUSDT",
    "ICPUSDT",
    "IMXUSDT",
    "INJUSDT",
    "JASMYUSDT",
    "JTOUSDT",
    "JUPUSDT",
    "KASUSDT",
    "LINKUSDT",
    "LTCUSDT",
    "MANAUSDT",
    "NEARUSDT",
    "ONDOUSDT",
    "OPUSDT",
    "ORDIUSDT",
    "PENDLEUSDT",
    "PYTHUSDT",
    "RENDERUSDT",
    "RUNEUSDT",
    "SEIUSDT",
    "SHIB1000USDT",
    "SOLUSDT",
    "STXUSDT",
    "SUIUSDT",
    "TAOUSDT",
    "TIAUSDT",
    "TONUSDT",
    "TRBUSDT",
    "TRXUSDT",
    "UNIUSDT",
    "VETUSDT",
    "WIFUSDT",
    "WLDUSDT",
    "XLMUSDT",
    "XRPUSDT",
]

DEFAULT_TICKERS = DEFAULT_UNIVERSE

CLUSTER_BY_SYMBOL = {
    "1000BONKUSDT": "meme",
    "1000FLOKIUSDT": "meme",
    "1000PEPEUSDT": "meme",
    "SHIB1000USDT": "meme",
    "WIFUSDT": "meme",
    "DOGEUSDT": "meme",
    "ADAUSDT": "majors",
    "TRXUSDT": "majors",
    "XLMUSDT": "majors",
    "XRPUSDT": "majors",
    "LINKUSDT": "majors",
    "LTCUSDT": "majors",
    "BCHUSDT": "majors",
    "APTUSDT": "layer1",
    "ATOMUSDT": "layer1",
    "AVAXUSDT": "layer1",
    "NEARUSDT": "layer1",
    "SEIUSDT": "layer1",
    "SOLUSDT": "layer1",
    "STXUSDT": "layer1",
    "SUIUSDT": "layer1",
    "TONUSDT": "layer1",
    "TAOUSDT": "ai",
    "RENDERUSDT": "ai",
    "WLDUSDT": "ai",
    "ARKMUSDT": "ai",
    "ARBUSDT": "l2",
    "OPUSDT": "l2",
    "MANAUSDT": "metaverse",
    "AXSUSDT": "gaming",
    "GALAUSDT": "gaming",
    "IMXUSDT": "gaming",
    "AAVEUSDT": "defi",
    "INJUSDT": "defi",
    "JTOUSDT": "defi",
    "JUPUSDT": "defi",
    "ONDOUSDT": "defi",
    "PENDLEUSDT": "defi",
    "RUNEUSDT": "defi",
    "UNIUSDT": "defi",
    "ENAUSDT": "defi_beta",
    "ORDIUSDT": "beta",
    "ETCUSDT": "pow",
    "FILUSDT": "infra",
    "HBARUSDT": "infra",
    "ICPUSDT": "infra",
    "JASMYUSDT": "infra",
    "KASUSDT": "infra",
    "PYTHUSDT": "infra",
    "TIAUSDT": "infra",
    "TRBUSDT": "infra",
    "VETUSDT": "infra",
    "ENSUSDT": "id",
    "DOTUSDT": "legacy_l1",
}


def ticker_cluster(ticker: str) -> str:
    return CLUSTER_BY_SYMBOL.get(ticker.upper(), ticker.upper())
